### ISSUE TITLE
[BUG] Setting Egg Gacha Type Freezes Tab - Firefox

### ISSUE THREAD

**Issue by Kaosys2775** [MikeyTheA/PokeRogueExtra#17]
When using the extension in Firefox, editing tier of egg works, but changing the Gacha type will freeze the tab, then allow movement with sound but the actual game doesn't show anything.

To Recreate:
1. Load extension via about:debugging > load temporary add-on > v1.2 manifest.json
2. Attempt to change Gacha type of all eggs under [Account Editor] > [Eggs] > [Set all eggs to GACHA TYPE]
3. It should open egg list, but will not update screen until you reload page, which then undos the set type. 

Running Firefox with standard privacy settings, PokeRogueExtra v1.2, also running Rogue Dex extension. Win10 AtlasOS.

**Comment by asfjyrgfs** [comment]
Hello! Are you using the UC build (little behind from the latest source on github) or are you building from github? This should have been fixed a while back, please reopen if building yourself, if you are make sure you've pulled the latest version.
